// Gastro Pack House - Product Catalog
// Imported from Barewoods Wholesale on 2026-05-07.

const CATEGORIES = [
  {
    "id": "lows",
    "name": "Lows",
    "count": 38
  },
  {
    "id": "zaa",
    "name": "Zaa",
    "count": 18
  },
  {
    "id": "indoors",
    "name": "Indoors",
    "count": 25
  },
  {
    "id": "exotics-indoors",
    "name": "Exotics Indoors",
    "count": 15
  },
  {
    "id": "snow-cap",
    "name": "Snow Cap",
    "count": 2
  },
  {
    "id": "moon-rocks",
    "name": "Moon Rocks",
    "count": 1
  },
  {
    "id": "shrooms",
    "name": "Shrooms",
    "count": 1
  },
  {
    "id": "concentrates",
    "name": "Concentrates",
    "count": 1
  }
];

const PRODUCTS = [
  {
    "id": 1,
    "slug": "black-runtz-lows",
    "cat": "lows",
    "name": "Black Runtz | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.37.52.jpeg"
  },
  {
    "id": 2,
    "slug": "lcg-nu-lows",
    "cat": "lows",
    "name": "LCG Nu | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.38.38.jpeg"
  },
  {
    "id": 3,
    "slug": "rainbow-cherry-lows",
    "cat": "lows",
    "name": "Rainbow Cherry | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.39.40.jpeg"
  },
  {
    "id": 4,
    "slug": "uncle-snoop-lows",
    "cat": "lows",
    "name": "Uncle Snoop | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.40.24.jpeg"
  },
  {
    "id": 5,
    "slug": "hichew-lows",
    "cat": "lows",
    "name": "Hichew | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.42.25.jpeg"
  },
  {
    "id": 6,
    "slug": "sour-diesel-lows",
    "cat": "lows",
    "name": "Sour Diesel | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-03.05.04.jpeg"
  },
  {
    "id": 7,
    "slug": "da-funk-lows",
    "cat": "lows",
    "name": "Da Funk | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-16.37.57.jpeg"
  },
  {
    "id": 8,
    "slug": "gusher-gelato-mixed-light",
    "cat": "lows",
    "name": "Gusher Gelato | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.23.40-1.jpeg"
  },
  {
    "id": 9,
    "slug": "key-lime-pie-mixed-light",
    "cat": "lows",
    "name": "Key Lime Pie | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.17.01-1.jpeg"
  },
  {
    "id": 10,
    "slug": "rs-1000-mixed-light",
    "cat": "lows",
    "name": "RS-1000 | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.29.40.jpeg"
  },
  {
    "id": 11,
    "slug": "fire-og-mixed-light",
    "cat": "lows",
    "name": "Fire OG | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-21.35.11-1.jpeg"
  },
  {
    "id": 12,
    "slug": "stardawg-mixed-light",
    "cat": "lows",
    "name": "Stardawg | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-21.37.51.jpeg"
  },
  {
    "id": 13,
    "slug": "butterface-mixed-light",
    "cat": "lows",
    "name": "Butterface | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.26.28-1.jpeg"
  },
  {
    "id": 14,
    "slug": "purple-voodoo-mixed-light",
    "cat": "lows",
    "name": "Purple Voodoo | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.29.57-2.jpeg"
  },
  {
    "id": 15,
    "slug": "fruit-punch-mixed-light",
    "cat": "lows",
    "name": "Fruit Punch | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.40.15-1.jpeg"
  },
  {
    "id": 16,
    "slug": "bigfoot-mixed-light",
    "cat": "lows",
    "name": "Bigfoot | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-17.38.10-1.jpeg"
  },
  {
    "id": 17,
    "slug": "blue-gushers-mixed-light",
    "cat": "lows",
    "name": "Blue Gushers | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.18.52-1.jpeg"
  },
  {
    "id": 18,
    "slug": "gods-glue-indoor",
    "cat": "lows",
    "name": "Gods Glue | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-01.35.15-1.jpeg"
  },
  {
    "id": 19,
    "slug": "tropical-jealousy-indoor",
    "cat": "lows",
    "name": "Tropical Jealousy | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-01.46.19-1.jpeg"
  },
  {
    "id": 20,
    "slug": "blue-nerds-indoor",
    "cat": "lows",
    "name": "Blue Nerds | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.14.15-1.jpeg"
  },
  {
    "id": 21,
    "slug": "cotton-candy-indoor",
    "cat": "lows",
    "name": "Cotton Candy | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-01.55.47.jpeg"
  },
  {
    "id": 22,
    "slug": "lcg-85-indoor",
    "cat": "lows",
    "name": "LCG #85 | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-01.58.29.jpeg"
  },
  {
    "id": 23,
    "slug": "monster-lcg-indoor",
    "cat": "lows",
    "name": "Monster LCG | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.03.25.jpeg"
  },
  {
    "id": 24,
    "slug": "pink-runtz-indoor",
    "cat": "lows",
    "name": "Pink Runtz | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.30.18-1.jpeg"
  },
  {
    "id": 25,
    "slug": "cherry-poppers-indoor",
    "cat": "lows",
    "name": "Cherry Poppers | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.10.49.jpeg"
  },
  {
    "id": 26,
    "slug": "sushi-indoor",
    "cat": "lows",
    "name": "Sushi | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.13.40.jpeg"
  },
  {
    "id": 27,
    "slug": "deleted-scenes-indoor",
    "cat": "lows",
    "name": "Deleted Scenes | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-00.33.51.jpeg"
  },
  {
    "id": 28,
    "slug": "gumbo-cherries-indoor",
    "cat": "lows",
    "name": "Gumbo Cherries | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.16.52.jpeg"
  },
  {
    "id": 29,
    "slug": "rainbow-zangria-indoor",
    "cat": "lows",
    "name": "Rainbow Zangria | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-23.32.26-2.jpeg"
  },
  {
    "id": 30,
    "slug": "trap-fuel-indoor",
    "cat": "lows",
    "name": "Trap Fuel | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-23.29.22-1.jpeg"
  },
  {
    "id": 31,
    "slug": "atomic-belts-indoor",
    "cat": "lows",
    "name": "Atomic Belts | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-23.37.42-1-1.jpeg"
  },
  {
    "id": 32,
    "slug": "scented-marker-indoor",
    "cat": "lows",
    "name": "Scented Marker | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-22.43.21.jpeg"
  },
  {
    "id": 33,
    "slug": "pineapple-fruz-x-permanent-marker-indoor",
    "cat": "lows",
    "name": "Pineapple Fruz x Permanent Marker | Lows",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-03.04.18.jpeg"
  },
  {
    "id": 34,
    "slug": "candy-ethos-exotic-indoor",
    "cat": "lows",
    "name": "Candy Ethos | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.23.13.jpeg"
  },
  {
    "id": 35,
    "slug": "permanent-marker",
    "cat": "lows",
    "name": "Permanent Marker | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.38.10.jpeg"
  },
  {
    "id": 36,
    "slug": "og-kush",
    "cat": "lows",
    "name": "OG Kush | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.34.17-1.jpeg"
  },
  {
    "id": 37,
    "slug": "ice-cream-cake",
    "cat": "lows",
    "name": "Ice Cream Cake | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.28.53-1.jpeg"
  },
  {
    "id": 38,
    "slug": "super-boof",
    "cat": "lows",
    "name": "Super Boof | Lows",
    "price": 550,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.05.44.jpeg"
  },
  {
    "id": 39,
    "slug": "ice-chain-gelato-mixed-light",
    "cat": "zaa",
    "name": "Ice Chain Gelato | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-03.05.29.jpeg"
  },
  {
    "id": 40,
    "slug": "sour-skittlez-mixed-light",
    "cat": "zaa",
    "name": "Sour Skittlez | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-18.10.34.jpeg"
  },
  {
    "id": 41,
    "slug": "bubba-kush-mixed-light",
    "cat": "zaa",
    "name": "Bubba Kush | Zaa",
    "price": 600,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.22.11-1.jpeg"
  },
  {
    "id": 42,
    "slug": "ultra-violet-mixed-light",
    "cat": "zaa",
    "name": "Ultra Violet | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.17.45-1.jpeg"
  },
  {
    "id": 43,
    "slug": "modified-grapez-mixed-light",
    "cat": "zaa",
    "name": "Modified Grapez | Zaa",
    "price": 650,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-21.29.45.jpeg"
  },
  {
    "id": 44,
    "slug": "animal-mintz-mixed-light",
    "cat": "zaa",
    "name": "Animal Mintz | Zaa",
    "price": 660,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.34.18.jpeg"
  },
  {
    "id": 45,
    "slug": "zoonami-indoor",
    "cat": "zaa",
    "name": "Zoonami | Zaa",
    "price": 600,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-23.22.37.jpeg"
  },
  {
    "id": 46,
    "slug": "blue-ritz-indoor",
    "cat": "zaa",
    "name": "Blue Ritz | Zaa",
    "price": 600,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-23.26.54.jpeg"
  },
  {
    "id": 47,
    "slug": "berry-latto-pop-indoor",
    "cat": "zaa",
    "name": "Berry Latto Pop | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.28.46.jpeg"
  },
  {
    "id": 48,
    "slug": "italian-candy-indoor",
    "cat": "zaa",
    "name": "Italian Candy | Zaa",
    "price": 600,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-02.54.06-1.jpeg"
  },
  {
    "id": 49,
    "slug": "pink-guava-runtz-indoor",
    "cat": "zaa",
    "name": "Pink Guava Runtz | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.31.12.jpeg"
  },
  {
    "id": 50,
    "slug": "rainbow-candy-za-indoor",
    "cat": "zaa",
    "name": "Rainbow Candy Za | Zaa",
    "price": 650,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.35.46.jpeg"
  },
  {
    "id": 51,
    "slug": "last-spooky-box-indoor",
    "cat": "zaa",
    "name": "Last Spooky Box | Zaa",
    "price": 600,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-03.02.08.jpeg"
  },
  {
    "id": 52,
    "slug": "wedding-cake-indoor",
    "cat": "zaa",
    "name": "Wedding Cake | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-29-at-23.14.16.jpeg"
  },
  {
    "id": 53,
    "slug": "pineapple-express-indoor",
    "cat": "zaa",
    "name": "Pineapple Express | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-03.06.17.jpeg"
  },
  {
    "id": 54,
    "slug": "purple-smalls-exotic-indoor",
    "cat": "zaa",
    "name": "Purple Smalls | Zaa",
    "price": 700,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.56.32-1.jpeg"
  },
  {
    "id": 55,
    "slug": "cures-exotic-indoor",
    "cat": "zaa",
    "name": "Cures | Zaa",
    "price": 600,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.59.00.jpeg"
  },
  {
    "id": 56,
    "slug": "gelato-41",
    "cat": "zaa",
    "name": "Gelato #41 | Zaa",
    "price": 650,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.45.48.jpeg"
  },
  {
    "id": 57,
    "slug": "promethzine-mixed-light",
    "cat": "indoors",
    "name": "Promethzine | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.17.35.jpeg"
  },
  {
    "id": 58,
    "slug": "gorilla-glue-4-indoor",
    "cat": "indoors",
    "name": "Gorilla Glue #4 | Indoors",
    "price": 950,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.03.07-2.jpeg"
  },
  {
    "id": 59,
    "slug": "blue-cookies-indoor",
    "cat": "indoors",
    "name": "Blue Cookies | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.20.16.jpeg"
  },
  {
    "id": 60,
    "slug": "gelonade-indoor",
    "cat": "indoors",
    "name": "Gelonade | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-02.08.06-1.jpeg"
  },
  {
    "id": 61,
    "slug": "novelty-candy-indoor",
    "cat": "indoors",
    "name": "Novelty Candy | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.26.10-1.jpeg"
  },
  {
    "id": 62,
    "slug": "blueberry-glaze-zonuts-indoor",
    "cat": "indoors",
    "name": "Blueberry Glaze Zonuts | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.27.53.jpeg"
  },
  {
    "id": 63,
    "slug": "truffle-candy-runtz-indoor",
    "cat": "indoors",
    "name": "Truffle Candy Runtz | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-02.56.48.jpeg"
  },
  {
    "id": 64,
    "slug": "snow-storm-indoor",
    "cat": "indoors",
    "name": "Snow Storm | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.45.05.jpeg"
  },
  {
    "id": 65,
    "slug": "blue-dream-indoor",
    "cat": "indoors",
    "name": "Blue Dream | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.50.10.jpeg"
  },
  {
    "id": 66,
    "slug": "platinum-cherriez-exotic-indoor",
    "cat": "indoors",
    "name": "Platinum Cherriez | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.27.20.jpeg"
  },
  {
    "id": 67,
    "slug": "blue-nerds-exotic-indoor",
    "cat": "indoors",
    "name": "Blue Nerds | Indoors",
    "price": 900,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.14.14.jpeg"
  },
  {
    "id": 68,
    "slug": "bolo-runtz-green-exotic-indoor",
    "cat": "indoors",
    "name": "Bolo Runtz Green | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.12.59.jpeg"
  },
  {
    "id": 69,
    "slug": "larry-bird-exotic-indoor",
    "cat": "indoors",
    "name": "Larry Bird | Indoors",
    "price": 900,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.27.32.jpeg"
  },
  {
    "id": 70,
    "slug": "zamosa-green-exotic-indoor",
    "cat": "indoors",
    "name": "Zamosa Green | Indoors",
    "price": 850,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.13.37.jpeg"
  },
  {
    "id": 71,
    "slug": "runtz",
    "cat": "indoors",
    "name": "Runtz | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.49.46-1.jpeg"
  },
  {
    "id": 72,
    "slug": "wedding-cake",
    "cat": "indoors",
    "name": "Wedding Cake | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.48.14-1.jpeg"
  },
  {
    "id": 73,
    "slug": "lemon-cherry-gelato",
    "cat": "indoors",
    "name": "Lemon Cherry Gelato | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.44.08-1.jpeg"
  },
  {
    "id": 74,
    "slug": "apples-and-bananas",
    "cat": "indoors",
    "name": "Apples and Bananas | Indoors",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.35.53.jpeg"
  },
  {
    "id": 75,
    "slug": "girl-scout-cookies",
    "cat": "indoors",
    "name": "Girl Scout Cookies | Indoors",
    "price": 850,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.32.24-1.jpeg"
  },
  {
    "id": 76,
    "slug": "sour-diesel",
    "cat": "indoors",
    "name": "Sour Diesel | Indoors",
    "price": 950,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.26.09-1.jpeg"
  },
  {
    "id": 77,
    "slug": "mimosa",
    "cat": "indoors",
    "name": "Mimosa | Indoors",
    "price": 850,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.20.30-1.jpeg"
  },
  {
    "id": 78,
    "slug": "gorilla-glue-4",
    "cat": "indoors",
    "name": "Gorilla Glue #4 | Indoors",
    "price": 950,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.17.37.jpeg"
  },
  {
    "id": 79,
    "slug": "cereal-milk",
    "cat": "indoors",
    "name": "Cereal Milk | Indoors",
    "price": 850,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.10.29.jpeg"
  },
  {
    "id": 80,
    "slug": "slurricane",
    "cat": "indoors",
    "name": "Slurricane | Indoors",
    "price": 950,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.03.07-2.jpeg"
  },
  {
    "id": 81,
    "slug": "last-badder-box-concentrate",
    "cat": "indoors",
    "name": "Last Badder Box -- Concentrate | Indoors",
    "price": 750,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-02.59.35-1.jpeg"
  },
  {
    "id": 82,
    "slug": "sunset-sherbert-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Sunset Sherbert | Exotics Indoors",
    "price": 1500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.52.37.jpeg"
  },
  {
    "id": 83,
    "slug": "white-himalaya-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "White Himalaya | Exotics Indoors",
    "price": 1500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.08.34-1.jpeg"
  },
  {
    "id": 84,
    "slug": "purple-mochi-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Purple Mochi | Exotics Indoors",
    "price": 1450,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.57.44-1.jpeg"
  },
  {
    "id": 85,
    "slug": "oreoz-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Oreoz | Exotics Indoors",
    "price": 1400,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.08.34-1.jpeg"
  },
  {
    "id": 86,
    "slug": "mac-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "MAC | Exotics Indoors",
    "price": 1400,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-02.05.17.jpeg"
  },
  {
    "id": 87,
    "slug": "uncle-snoop-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Uncle Snoop | Exotics Indoors",
    "price": 1500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-02.06.04.jpeg"
  },
  {
    "id": 88,
    "slug": "blackberry-kush-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Blackberry Kush | Exotics Indoors",
    "price": 1500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-21.57.46.jpeg"
  },
  {
    "id": 89,
    "slug": "silverback-gorilla-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Silverback Gorilla | Exotics Indoors",
    "price": 1400,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-02.52.44-1.jpeg"
  },
  {
    "id": 90,
    "slug": "berry-blast-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "Berry Blast | Exotics Indoors",
    "price": 1000,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.15.43.jpeg"
  },
  {
    "id": 91,
    "slug": "bx-1-exotic-indoor",
    "cat": "exotics-indoors",
    "name": "BX-1 | Exotics Indoors",
    "price": 1000,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.16.20.jpeg"
  },
  {
    "id": 92,
    "slug": "blue-dream",
    "cat": "exotics-indoors",
    "name": "Blue Dream | Exotics Indoors",
    "price": 1000,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.42.04.jpeg"
  },
  {
    "id": 93,
    "slug": "granddaddy-purple",
    "cat": "exotics-indoors",
    "name": "Granddaddy Purple | Exotics Indoors",
    "price": 1500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.24.08-1.jpeg"
  },
  {
    "id": 94,
    "slug": "pineapple-express",
    "cat": "exotics-indoors",
    "name": "Pineapple Express | Exotics Indoors",
    "price": 1200,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.16.00.jpeg"
  },
  {
    "id": 95,
    "slug": "biscotti",
    "cat": "exotics-indoors",
    "name": "Biscotti | Exotics Indoors",
    "price": 1200,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.13.06.jpeg"
  },
  {
    "id": 96,
    "slug": "white-widow",
    "cat": "exotics-indoors",
    "name": "White Widow | Exotics Indoors",
    "price": 1200,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-31-at-05.08.34-1.jpeg"
  },
  {
    "id": 97,
    "slug": "new-bounty-box-snow-caps-exotic-indoor",
    "cat": "snow-cap",
    "name": "New Bounty Box Snow Caps | Snow Cap",
    "price": 900,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.36.07.jpeg"
  },
  {
    "id": 98,
    "slug": "candy-runtz-snow-caps-exotic-indoor",
    "cat": "snow-cap",
    "name": "Candy Runtz Snow Caps | Snow Cap",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-22-at-22.36.07.jpeg"
  },
  {
    "id": 99,
    "slug": "muun-moonrocks",
    "cat": "moon-rocks",
    "name": "Muun Moonrocks | Moon Rocks",
    "price": 800,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.21.43.jpeg"
  },
  {
    "id": 100,
    "slug": "shrooms",
    "cat": "shrooms",
    "name": "Shrooms",
    "price": 500,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-27-at-01.28.34-1.jpeg"
  },
  {
    "id": 101,
    "slug": "premium-liquid-concentrate",
    "cat": "concentrates",
    "name": "Premium Liquid -- Concentrate | Lows",
    "price": 540,
    "unit": "/lb",
    "stock": "In Stock",
    "moq": "1 lb",
    "image": "https://barewoodwholesale.com/images/products/WhatsApp-Image-2026-03-30-at-03.42.29.jpeg"
  }
];
